mail_user": "YOURMAILHERE@example.com"
input_list_file: "input_list_example.tab"
batches_done_file: "other/batches_done_example.tab"
input_base: "input"
output_base: "output"
reference: "artic-ncov2019/primer_schemes/SARS-CoV-2/V3/nCoV-2019.reference.fasta"
bed_file: "artic-ncov2019/primer_schemes/SARS-CoV-2/V3/nCoV-2019.primer.bed"
singularity_images: "~/.singularity/docker"
conda_base: "~/miniconda3"
conda_env: "ivar-inpipe"